// This code was mostly generated by Google Gemini with various tweaks.
// It is only supported on Teensy microcontrollers since it uses an
// IntervalTimer object.

#ifndef STEPPER_28BYJ48_H
#define STEPPER_28BYJ48_H

#include "Arduino.h"

// This class controls a 28BYJ48 stepper motor.  It uses the Teensy 4 IntervalTimer
// consistent timing of the motor steps.

class Stepper28BYJ48
{
public:
    Stepper28BYJ48(int pin1, int pin2, int pin3, int pin4, float max_steps_per_sec, float acceleration);
    ~Stepper28BYJ48();

    bool move_to_position(long position);
    void set_osc_mode(long position);
    long get_position() const;
    long get_target_position() const;
    bool at_position() const;

    void set_current_pos(long position);
    void stop();

    long get_steps_per_rev() const;

    friend void step_motor_isr();

private:
    void update();
    void finished();

    const int stepper_pins_[4] = {-1,};
    bool inited_{false};

    IntervalTimer stepTimer_;
    volatile int cur_seq_index_{0};

    volatile bool run_{false};

    // Position Variables
    volatile long cur_pos_{0};              // Current absolute step position
    volatile long target_pos_{0};           // Target absolute step position
    volatile long osc_mode_pos_{0};         // Oscillation mode +/- position

    // Motion Profile Variables
    volatile float cur_speed_{0.0f};        // Steps per second
    volatile float max_speed_{1500.0f};     // Max speed ceiling
    volatile float min_speed_{40.0f};       // Minimum speed to avoid stalling
    volatile float acceleration_{2000.0f};  // Steps per second^2
    volatile float cur_interval_{25000.0f}; // Microseconds
};

#endif // STEPPER_28BYJ48_H
