; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = teensy
framework = arduino
upload_port = /dev/ttyACM0
upload_protocol = teensy-cli
board_microros_transport = serial
board_microros_distro = lyrical
build_flags = -I ../config
	-D ELSABOT
	-Wno-unused-result

[env:teensy41]
board = teensy41
board_microros_user_meta = micro_ros.meta
lib_deps = 
	https://github.com/hippo5329/micro_ros_platformio.git
	https://github.com/rshorton/Adafruit_VL53L7.git
	stm32duino/STM32duino VL53L7CX@^1.0.3
	robtillaart/PCF8575@^0.3.0
